import { getAuthGroups } from '@/api/authGroups'
import { USER_ROLES } from '@/domain/role'

export default [
  {
    type: 'Input',
    key: 'id',
    position: 1,
    placeholder: 'ID',
    access: ['administrator', 'it', 'manager'],
  },
  {
    type: 'Input',
    key: 'lastName',
    position: 2,
    placeholder: 'Фамилия',
    mode: 'ilike',
    access: ['administrator', 'it', 'manager'],
  },
  {
    type: 'Input',
    key: 'firstName',
    position: 3,
    placeholder: 'Имя',
    mode: 'ilike',
    access: ['administrator', 'it', 'manager'],
  },
  {
    type: 'Input',
    key: 'middleName',
    position: 4,
    placeholder: 'Отчество',
    mode: 'ilike',
    access: ['administrator', 'it', 'manager'],
  },
  {
    type: 'Input',
    key: 'email',
    position: 5,
    placeholder: 'Email',
    mode: 'ilike',
    access: ['administrator', 'it', 'manager'],
  },
  {
    type: 'Input',
    key: 'phone',
    position: 6,
    placeholder: 'Номер телефона',
    mode: 'ilike',
    access: ['administrator', 'it', 'manager'],
  },
  {
    type: 'DateRange',
    key: 'created-at',
    position: 7,
    placeholder: 'Дата создания',
    mode: 'dateRange',
    access: ['administrator', 'it', 'manager'],
  },
  {
    type: 'AsyncSelect',
    dataSource: getAuthGroups,
    valueKey: 'id',
    nameKey: 'name',
    key: 'auth-group-id',
    position: 8,
    placeholder: 'База пользователей',
    multiple: false,
    access: ['administrator', 'it', 'manager'],
  },
  {
    type: 'Select',
    data: Object.values(USER_ROLES),
    key: 'authAssignments.itemName',
    position: 9,
    placeholder: 'Роль',
    access: ['administrator', 'it', 'manager'],
  },
]
