export default [
  {
    type: 'Input',
    key: 'id',
    position: 1,
    placeholder: 'ID карточки',
    label: 'ID карточки',
    searchable: true,
    access: ['administrator', 'it', 'manager'],
  },
  {
    type: 'Input',
    key: 'email',
    position: 2,
    placeholder: 'Email',
    label: 'Email',
    searchable: true,
    access: ['administrator', 'it', 'manager'],
  },
  {
    type: 'TurboMultiSelect',
    key: 'base_id',
    position: 3,
    placeholder: 'База пользователей',
    label: 'База пользователей',
    searchable: true,
    access: ['administrator', 'it', 'manager'],
  },
  {
    type: 'Input',
    key: 'fio',
    position: 4,
    placeholder: 'ФИО',
    label: 'ФИО',
    searchable: true,
    access: ['administrator', 'it', 'manager'],
  },
  {
    type: 'TurboMultiSelect',
    key: 'region',
    position: 5,
    placeholder: 'Область',
    label: 'Область',
    searchable: true,
    access: ['administrator', 'it', 'manager'],
  },
  {
    type: 'TurboMultiSelect',
    key: 'city',
    position: 7,
    placeholder: 'Город',
    label: 'Город',
    searchable: true,
    access: ['administrator', 'it', 'manager'],
  },
  {
    type: 'TurboMultiSelect',
    key: 'position',
    position: 8,
    placeholder: 'Должность',
    label: 'Должность',
    searchable: true,
    access: ['administrator', 'it', 'manager'],
  },
  {
    type: 'TurboMultiSelect',
    key: 'specialty',
    position: 9,
    placeholder: 'Специальность',
    label: 'Специальность',
    searchable: true,
    access: ['administrator', 'it', 'manager'],
  },
  {
    type: 'TurboMultiSelect',
    key: 'specialization',
    position: 10,
    placeholder: 'Специализация',
    label: 'Специализация',
    searchable: true,
    access: ['administrator', 'it', 'manager'],
  },
  {
    type: 'TurboMultiSelect',
    key: 'event_id',
    position: 11,
    placeholder: 'Мероприятие',
    label: 'Мероприятие',
    searchable: true,
    access: ['administrator', 'it'],
  },
]
